openapi: 3.0.0
info:
  title: TensorFlow Resnet API by Ainize
  version: 0.1.1
servers:
  - url: http://34.85.117.64:8501/v1/models
paths:
  /resnet:
    get:
      operationId: status
      summary: Get status
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              examples:
                pooh:
                  value:
                    model_version_status:
                      - version: '1538687457'
                        state: 'AVAILABLE'
                        status:
                          error_code: 'OK'
                          error_message: ''
  /resnet/metadata:
    get:
      operationId: metadata
      summary: Get model's metadat
      responses:
        '200':
          description: 200 response
  /resnet:predict:
    post:
      operationId: predict
      summary: Predict object class of given image
      requestBody:
        description: subscription payload
        content:
          application/json:
            schema:
              type: object
              properties:
                instances:
                  type: array
                  items:
                    type: object
                    properties:
                      b64:
                        type: string
                        format: byte # base64-encoded image file contents
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              examples:
                pooh:
                  value:
                    predictions:
                      - classes: 208
                        probabilities:
                        - '1.32371497e-06'
                        - '9.01561236e-07'

